/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CropModal: typeof import('./src/components/dialogs/CropModal.vue')['default']
    DeleteAnnotationDialog: typeof import('./src/components/dialogs/DeleteAnnotationDialog.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MsAdd: typeof import('~icons/material-symbols/add')['default']
    MsClose: typeof import('~icons/material-symbols/close')['default']
    MsDelete: typeof import('~icons/material-symbols/delete')['default']
    MsDownload: typeof import('~icons/material-symbols/download')['default']
    MsEdit: typeof import('~icons/material-symbols/edit')['default']
    MsSave: typeof import('~icons/material-symbols/save')['default']
    MsSettings: typeof import('~icons/material-symbols/settings')['default']
    MsUpload: typeof import('~icons/material-symbols/upload')['default']
    NotificationArea: typeof import('./src/components/NotificationArea.vue')['default']
    ResizeHandle: typeof import('./src/components/ResizeHandle.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UploadZoneModal: typeof import('./src/components/dialogs/UploadZoneModal.vue')['default']
  }
}
